### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Ghost0159** [ghost-land/3dserver#11]
# To do :

**WebUI :**
- [ ] Add an RSS feed where you can see the latest games added
- [ ] Fix thumbnails (in the db they are like that: ``http://thumbnail1.jpg \ http://thumbnail2.jpg \ http://thumbnail3.jpg``)
- [ ] Add ScreenShots and icon(48x48) to game sheet
- [ ] Display game rankings
- [ ] Add a system where users can post comments under games, with a system where admins and moderators have to approve a comment for it to be visible to everyone
- [ ] Add all the information available on a game, such as: game languages, game size (converted to block, MiB/GiB), region
- [ ] Add a filter system by region
- [ ] Improve game search functions (by tID, Product Code, keyword...)
- [ ] (optional) Add a forum
- [ ] Add download button for : .3ds, .cia, .cxi, .3dsx (.cxi for CITRA)
- [ ] Add how many times each game has been downloaded

**3DS :**
- [ ] Fix keywords
- [ ] Add mp4 videos to game files in nintendo eShop
- [ ] Implement the voting function
- [ ] Implement Ranking
- [ ] Add a filter system by region
- [ ] Add the game region before going to the game sheet
